Mboalab/Outreachy_May_2023-August_2023-Internships

Improve a digital Stethoscope app/Tasks/Starter tasks/Task 0
=> Updated Task0

Create a platform to link-up medical facilities globally/Tasks/Starter task/Task 0
=> Update Task 0

Create a platform to link-up medical facilities globally/Applicants/Mohamed-Ali-Ibrahim/introduction.md, Create a platform to link-up medical facilities globally/Applicants/Mohamed-Ali-Ibrahim/task0.md
Hi, 
I have made a change within the "Create a platform to link-up medical facilities globally" folder
added: 
- folder name: Mohamed Ali Ibrahim
- within the folder added an md file named introduction.md
=> Create Mohamed ali's introduction.md and task0.md

Create a platform to link-up medical facilities globally/Applicants/Ngobiri-Falyne-Chinaero/Introduction.md
Contributing to create a platform to link-up medical facilities globally
=> Introduction-Ngobiri-Falyne

Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Introduction.md, Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Starter Tasks/Task0.md, Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Starter Tasks/Task1.md
This PR adds the Google Form data collection tool for hospitals, allowing them to sign up for the system and provide essential information about their name, location, services and facilities available, among other relevant information.
The form is designed in a user-friendly and organized manner to ensure ease of use for hospital staff. 
Included as well is the documentation outlining the tool's purpose, design, and usage instructions for both hospitals and system administrators.
=> Creating and Documenting the Data Collection Tool for Hospitals

Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Introduction.md, Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Starter Tasks/Task0.md
I have created a list of 50 active global hospitals. The hospitals were researched based on the criteria of being general medical facilities with co-existing sub-units. Each hospital in the list includes its location, services offered, and a link to its official website.
The research was conducted using a variety of sources including online directories of hospitals, government health agency websites, and international healthcare organizations' databases. All sources used are cited in the accompanying Task0 file.
I hope that this list of hospitals will be useful for linking up medical facilities around the world and improving global healthcare access.
=> I have curated a list of 50 Active Global Hospitals

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/Task 1/AnishaSingh.md
Hey, 👋😊
Added Introduction file as part of Starter Task.
Great full to be a part of this amazing open source community.
=> Introduction (AnishaSingh)

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/EmmillyNamuganga.md
Adds a folder named  'Applicants Contribution' under Starter Tasks and a file 'EmmillyNamuganga.md' which is a description of myself
=> Task 1 Introduction

Create a platform to link-up medical facilities globally/Applicants/PALAK/introduction.md
I'm Palak. Here I introduced me with some description.
=> Introduction

Create a platform to link-up medical facilities globally/Applicants/JENNIFER_EGERE/introduction.md, Create a platform to link-up medical facilities globally/Applicants/JENNIFER_EGERE/task0.md
Hi @PetraAG I'm Jennifer, I have completed the Introduction task for project #1
I've also added my task 0 for the starter task to this PR; Kindly ignore the first task0.md file as the updated one is right under it.
=> Here is my introduction.

Create a platform to link-up medical facilities globally/Applicants/Motunrayo_Agoro/introduction.md
tis is my introduction to be a part of the project
=> My introduction

Create a platform to link-up medical facilities globally/Applicants/Ihimbru Kanyimi Ihimbru/Introduction.md, Create a platform to link-up medical facilities globally/Tasks/Ihimbru Kanyimi Ihimbru/Introduction.md
Please consider only the first file created in the "Applications" folder and not the second
=> My Introduction - Ihimbru Kanyimi

.idea/.gitignore, Improve a digital Stethoscope app/Applicants Contribution/logickoder/logickoder.md
This pull request contains a file with a brief and accurate description of myself. I followed some tips from online sources to make the description interesting and relevant. I also included some links to my social media profiles. Please review and merge if everything looks good. Thank you.
=> A personal description of myself

Create a platform to link-up medical facilities globally/Applicants/Mwafrika_Mufungizi_Josue/introduction.md
1) I clearly Introduced myself
2) I highlighted my skills in the software development field
3) I added my contact details including; `My personal website`, `LinkedIn profile`,` GitHub profile`, `email` and `phone number`
=> Add introduction about myself and my skills

Create a platform to link-up medical facilities globally/Applicants/Chidimma_Madu/Introduction.md, Create a platform to link-up medical facilities globally/Applicants/Chidimma_Madu/Starter task/Task 0.md
I've created my introduction and have completed Task0
=> My Introduction - Chidimma Madu

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Introduction
This is a file that contains my introduction message to this project as an outreachy applicant.
=> Created a file for my introduction (Emmanuella's)

Improve a digital Stethoscope app/Tasks/Starter tasks/Yogita Tufchi/Task1.md
Creating a PR to merge m introduction.
=> Task 1- Added My introduction

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/NityaPasrija.md
@PetraAG 
The Readme file now includes updates on the Introduction and Starter tasks.
=> Nitya Pasrija: Introduction and Starter Tasks

Create a platform to link-up medical facilities globally/Applicants/Mohammed Mustafa Ali/Introduction.md
Good Morning Esteemed Mentors !
I have created my P.R request for my Introduction if all goes well, I will be delighted if you may accept my P.R.
Thank you so much !
=> Introduction of Mohammed Mustafa Ali

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/dhruvgupta.md
I have created a .md file as specified in task 1 of stethoscope project.
This file contains my introduction.
=> Starter Task Completed file : dhruvgupta.md

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicant contribution/KrishnaMehta.md
Added a applicant contribution folder and added my introduction.
=> Krishna Mehta Introduction

Improve a digital Stethoscope app/Tasks/Applicants Contribution/jeremiah chinedu.md
Hi team,
I reviewed the changes in this pull request and everything looks good to me. The new .md file for Jeremiah Chinedu is a great addition to our team's repository. I appreciate the effort put into providing a clear and concise bio for Jeremiah that highlights his skills, experience, and interests.
I also appreciate the attention to detail in the commit message and description, which provide a clear and informative summary of the changes made.
Based on my review, I'm happy to approve this pull request and merge it into the main branch. Great work, everyone!
=> Add bio for Jeremiah Chinedu, Outreachy applicant

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/Task 1/SumayaAhmedSalihs.md
This file is for the submission for Task 1 of Starter tasks.
=> Adds file of SumayaAhmedSalihs.md

Applicants Contribution/SimranPattnaik.md
As the Task 1 of Starters tasks, a folder with name "Applicants Contribution" is created and a file with name "SimranPattnaik.md" is added which has my introduction.
=> Task 1 of Starters tasks

Create a platform to link-up medical facilities globally/Applicants/Susan Ndibe
ABOUT ME:
I am a product designer and User research is my strongest suit. I am very interested in healthcare particularly in Nigeria, because I have 3 special needs dependants. I believe contributing to this project will improve the life of citizens in 3rd world countries like Nigeria, especially as many doctors have been  relocating to wester countries with better pay packages. My contact details are:
Email: Alisa2susan@gmail.com
Behance: https://www.behance.net/alisasusanN
I look forward to learning and contributing to this project.
=> Susan Ndibe

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Introduction.md
I have created my folder in the directory, and I have written my introduction.
=> introduction.md

Open Pay: The Open Source Payment technology for small change scarcity Mentor actions/Applicants/RICHARD DUSHIME/introduction.md, Open Pay: The Open Source Payment technology for small change scarcity Mentor actions/Applicants/RICHARD DUSHIME/task0.md, README.md
- Created  an Applicants Folder In the Open Pay Folder to make it organised 
Introduced my self and worked on task 0  i also updated the main repository links for PR, Fork,stars and issues  counter
=> introduction and task0

Create a platform to link-up medical facilities globally/Applicants/Mohamed-Ali-Ibrahim/task1.md
Hi, made changed to my applicant folder :added Task1 - "Data collection" kindly review :)
=> added task1: data collection

Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Advanced Task/Assets/README.md, Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Starter Tasks/Task0.md, Create a platform to link-up medical facilities globally/Applicants/Deborah Adeoye/Starter Tasks/Task1.md
I have updated the link to the tool. It should be accessible now.
Thank you @PetraAG
=> Updating the link to the tool

Create a platform to link-up medical facilities globally/Applicants/Nuibim Lewin/Advanced Task/research.md, Create a platform to link-up medical facilities globally/Applicants/Nuibim Lewin/Starter Task/Task 0.md
Conducted UX Research for the application to Link up Medical facilities. Includes, basic must have features, nice to have features, potential target audience and personas, as well as some technical considerations.
=> Advanced Task, Conducted UX Research on Application to Link up Medical Facilities.

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Starter Tasks/Task0.md
This file contains my submission for Task 0 - Research and create a list of 50 active global hospitals
=> Create a file for Task 0 submission

Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicant's Contribution/README.md, Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicant's Contribution/trainthesound.md
1. Added the demo video of the advanced task.
2. Added the code of the advanced task .
3. Added the trainthesound.md file.
https://user-images.githubusercontent.com/57020210/226273014-096b1864-6f69-48d5-a8d1-f6bcef445ae1.mp4
=> Adds Advanced task code , video recording and trainthesound.md file 

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicant Contributions/Video recording.md
**Link  to Video:** 
https://user-images.githubusercontent.com/86596711/226517504-af88b2f2-97c7-41cc-9254-9510e8125988.mp4
**Link to PR :** https://github.com/ruqaiyasattar/digitalstethoecopeAI/pull/17
=> Added video recording of advanced task

Improve a digital Stethoscope app/Tasks/Starter tasks/Applicant Contributions/Advanced task.md, Improve a digital Stethoscope app/Tasks/Starter tasks/Applicant Contributions/Advanced_task_Dhruv_Gupta.md, Improve a digital Stethoscope app/Tasks/Starter tasks/Applicant Contributions/Research_based_Task.md
Completed the task to research about the machine learning algorithms to train sound file.
=> Research based task ✅ - Dhruv Gupta

Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Introduction.md
Hey, 👋😊
Added Introduction file as part of Starter Task.
Grateful to be a part of this amazing open source community.
=> Introduction ( Anisha Singh)

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Advanced Task/Advance task.md
A file to contain my documentation for the advanced task. Mainly aimed at breaking down the task into milestones and documenting the process.
=> Created advance task file

Create a platform to link-up medical facilities globally/Applicants/Bilikis Sulaimon/task0.md, Create a platform to link-up medical facilities globally/Applicants/Bilikis Sulaimon/task1.md
Task0- List Of Active Hospitals Globally
=> List of Active Hospitals

Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Task1.md
My **Data Collection Tool** App is versatile and adaptable, as it can seamlessly operate on both Android devices and desktop computers thanks to its responsive design.
**Tool:** https://hospitalrecord.daisyjohnson4.repl.co/create
**Link:** https://hospitalrecord.daisyjohnson4.repl.co/, 
**Username:** anisha.singh0118@gmail.com
**Password:** Admin@12345.
=> Completed Task 1: For #Project 1(Data Collection Tool)

Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Task0.md
**This PR of mine is created to complete Task 0:**
Listed in Project 1 (Create a platform to link-up medical facilities globally)
Starter Tasks section.
**Research**
Document Link : (https://docs.google.com/document/d/11ItNqsjKIXz3N6_kVG3h3qnA9iTdjh2rnpnSE3GU5vg/edit?usp=sharing)
- I have kept in mind the authenticity of the Hospitals List.
- Included a small description, specialties, and link to their official websites.
- These Hospitals are well researched in terms of primary care hospitals like PHCs, CHCs, secondary care hospitals like District hospitals and tertiary care hospital associated with medical college.
- Including general hospitals with subdivisions.
**Here are few names of the Hospitals:**
1. All India Institute of Medical Sciences - Delhi (All India Institute of Medica)
2. …
=> Completed Task 0: For #Project 1 (List of 50 active Global Hospitals)

Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicants Contribution/SumayaAhmedSalihs/trainthesound.md
Hello @ruqaiyasattar,
I hope you are good. Please this is my submission for the Additional task of the digitalstethoecopeAI app. 
It contains my research finding of how to train a sound file using a simple machine learning algorithm.
Thank you.
=> Adds trainthesound.md file - Sumaya Ahmed Salihs

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Henrietta Ijenebe/Introduction.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Henrietta Ijenebe/Task0.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Henrietta Ijenebe/Task1.md
Hello Mentors... @Fadanka @PetraAG @ruqaiyasattar @jafsia  
I am Henrietta Ijenebe from Lagos Nigeria and I am working on the Outreachy  Open Source Payment Project.
I worked on my Introduction, task 0 and task 1 respectively.
=> Open Pay Project startertask

Create a platform to link-up medical facilities globally/Applicants/Motunrayo_Agoro/task0.md, Create a platform to link-up medical facilities globally/Applicants/Motunrayo_Agoro/task1.md
here is  my finished task for Task0 - Lists of 50 hospitals and Task1 Data collection tool
=> task0 Lists of Hospitals and task1 Data collection

Create a platform to link-up medical facilities globally/Applicants/Chidimma_Madu/Advanced Task/User Research.md, Create a platform to link-up medical facilities globally/Applicants/Chidimma_Madu/Starter task/Task 1.md
I Completed Task 1 (data Collection Tool)
=> Update Task 1

Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicant's Contribution/README.md, Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/EmmillyNamuganga.md
1. Added a link to the README.md for the Advanced task PR on the digitalsthethoscope.
ie https://github.com/ruqaiyasattar/digitalstethoecopeAI/pull/23
2. Edited content of EmmllyNamuganga.md file that has my introduction.
=> Adds Link to Advanced Task PR  and edit introduction.

Create a platform to link-up medical facilities globally/Applicants/EmmillyimmaculateNamuganga/Introduction.md, Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicant's Contribution/README.md, Improve a digital Stethoscope app/Tasks/Starter tasks/Applicants Contribution/EmmillyNamuganga.md
1. Adds a folder EmmillyimmaculateNamugaga to Applicants in Create a platform to link-up medical facilities globally
2. Adds a folder StarterTasks in EmmillyimmaculateNamugaga  folder
3. Adds a  folder AdvancedTasks in EmmillyimmaculateNamugaga folder
4. Adds file Introduction.md in EmmillyimmaculateNamugaga folder .
=> Adds  introduction to Create a platform to link-up medical facilities globally

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Starter Tasks/Starter Tasks/Task 1.md
I changed the description of Starter Task 1 to Hospital Data Collection Tool for easy identification.
=> Hospital Data Collection Tool

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Starter Tasks/Task1.md
Created a file to contain my submission for task 1; creating a hospital data collection tool
=> Created a file for Task 1 submission

Create a platform to link-up medical facilities globally/Applicants/Earl-Millen Toh Akwe/Create a platform to link medical facilities globally/Starter Tasks/Task 0.md, Create a platform to link-up medical facilities globally/Applicants/Earl-Millen Toh Akwe/improve a digital Stethoscope app/Starter Tasks/Task 0.md, Create a platform to link-up medical facilities globally/Applicants/Earl-Millen Toh Akwe/open Pay-The Open Source Payment Technology for small change scarcity/Starter Tasks/Task 0.md
Added my contributions to the task 0 of all starter task for the projects
=> Akwe afriitech patch 3

Create a platform to link-up medical facilities globally/Applicants/Mwafrika_Mufungizi_Josue/task1.md, Create a platform to link-up medical facilities globally/Applicants/Susan Ndibe
gather pertinent information about the hospital, such as its name, location, services provided, facilities available, and other 
pertinent information.
=> Add data collection tool to support our research

Create a platform to link-up medical facilities globally/Applicants/Nuibim Lewin/Starter Task/Task_1.md
Task 1.
Hello,
This is a proposed UI design and app for the data collection tool for the platform to link up medical facilities. This tool is envisioned as an easy-to-use Web app, which will be developed with Flutter, and hosted online. The tool is meant mainly for hospital administrators where they can add their hospitals
=> Task 1 - Create a Data Collection Tool for medical facilities - Lewin

Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicants Contribution/Applicant's Contribution/README.md, Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicants Contribution/Applicant's Contribution/trainthesound.md, Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicants Contribution/Emmillynamuganga/README.md, Improve a digital Stethoscope app/Tasks/Advanced  tasks/Applicants Contribution/Emmillynamuganga/trainthesound.md
Hi @ruqaiyasattar 
1. I have edited the trainthesound.md file after doing more research.
2. Placed my contribution in the Applicants Contribution folder
3. Added new recording of the final application 
4. Updated code at PR ->  https://github.com/ruqaiyasattar/digitalstethoecopeAI/pull/23
https://user-images.githubusercontent.com/57020210/228322784-11009c42-b451-4395-8faa-cc6013d55ebd.mp4
Any reviews are welcome.
=> Update recording and edit trainthesound.md

Create a platform to link-up medical facilities globally/Applicants/StephenMbubah/advanced/app github link
Advanced task for medical linkup task.
github link to the app repo is contained within
=> Advanced task for medical linkup task

Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Advance Task/ScreensTask1.md
- **Task goal**: Showcase design concept or preview for Hospital Link up App.
- **Dual focus**: Address needs and preferences of users and registrars.
- **Specifically** cater to hospitals looking to list themselves.
My goal was to create a logo that would not only represent a medical app with its heart pulse(/beat) design but also incorporate my organization's identity, which starts with the letter M.
https://www.figma.com/file/VzBFiL1lcARrRwa7LoX7bm/Untitled?node-id=3%3A84&t=2TfTi8hoQumXqJJl-1
=> Created Screens for Advance Task (#Project 1)

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Advanced Task/Research.md
This file contains my research for the hospital link up application
=> Created a file for my research

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Makinde Oluwafunmilayo Rebecca/introduction.md
@ruqaiyasattar @Fadanka @PetraAG @jafsia here is my introduction file
=> submit introduction

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Makinde Oluwafunmilayo Rebecca/Starter task/task0.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Makinde Oluwafunmilayo Rebecca/introduction.md
@Fadanka @jafsia @ruqaiyasattar @PetraAG here is a submission for my task o
=> submit task 0

Create a platform to link-up medical facilities globally/Applicants/StephenMbubah/advanced/app github link, Create a platform to link-up medical facilities globally/Applicants/StephenMbubah/advanced/new commit
Ive made changes to the application 
Adding a sign up pages for both hospital and patients
=> New branch

Create a platform to link-up medical facilities globally/Applicants/PALAK/Advance_Task.md
- I have created a Link-up Hospital Application, which includes four screens. Welcome screen, Login screen, Signup screen, and the main screen. Hew of colors used for an application is synchronized with the Data collection tool that was created in the last task.[ Here is the link to the tool](https://github.com/Palaktahlyani/Data_collection_tool).
- I made a logo, which can be improved as not much information was mentioned. I have added a video in the README file.
**It is not the final plan, It can be improved according to the feedback.**
-- Your feedback is important to me. Please let me know your thoughts.
=> Advance_Task-Project 1

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Daniel Eniola Olatunji/Advanced-Task/advanced-task.md
Added Brand Overview to the advanced-task.md.
@Fadanka
=> Open Pay Advanced Task: Added Brand Overview to advanced-task.md

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Advanced Task/Advance task.md
I removed the timeline based on feedback from Mentor Petra. 
I also broke down some milestones which were compounded. 
I corrected the numbering which was not in order due to additional milestones that were added.
=> Updated the file

Create a platform to link-up medical facilities globally/Applicants/Mohammed Mustafa Ali/Advanced Tasks/medicalfacilites.md
Respected Mentors !
I forgot to mention the Figma File Design Link in the ReadMe Section of the Advanced Tasks Folder and also added some instructions on how to run the app on devices.
I request my esteemed mentors to merge it !
Thanks and Regards
Mohammed Mustafa Ali
=> Added the Figma Design File in the ReadMe Section of the Advanced Tasks.

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/Brand color.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/Brand identity or name.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/Research on existing similar solution.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/brand logo/Brand logo explained.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/brand logo/Logo Style 1.md, Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/Motunrayo Agoro/Advance task/brand logo/Logo style 2.md
This  tasks for Open pay advance task is on 
Research on already existing solution
Brand identity/name
Brand color
Brand logo
=> Advance task- Research on already existing solution and Brand identity, Brand color, Brand logo

Create a platform to link-up medical facilities globally/Applicants/Makinde Oluwafunmilayo Rebecca/Starter tasks/Task1.md
@jafsia @PetraAG Here is my submission for task 1: Create a tool
=> Task 1 submission

Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task0.md, Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task1.md
Hello @PetraAG @ruqaiyasattar 
Hope you are doing well?
Here is my PR for task0 creating a list of 50 hospitals.
=> Task0 list of 50 hospitals 

Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Tas1 data collection tool.md, Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task0.md, Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task1.md
Hello @PetraAG @ruqaiyasattar 
Hope you are doing good?
I created a PR for data collection tools and i am requesting for your review.
=> Task1 data collection tool

Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Advancedtasks.md, Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task0.md, Create a platform to link-up medical facilities globally/Applicants/Balogun Elizabeth/Task1.md
Hello @PetraAG @ruqaiyasattar 
Hope you are doing well?
I have worked on an application that link up hospitals locally and globally, and in the google doc, contains the links of my designs and prototyping. [proposed application](https://docs.google.com/document/d/1cJdHoabSVJla7I-13svB9J0unJcCl5NCkPkbR9jtf_I/edit?usp=sharing)
Kindly requesting for your review.
=> Advancedtasks

Create a platform to link-up medical facilities globally/Applicants/Makinde Oluwafunmilayo Rebecca/Starter tasks/Task1.md, Create a platform to link-up medical facilities globally/Applicants/Makinde Oluwafunmilayo Rebecca/advanced task/advancedTask.md
Hello @PetraAG @jafsia here is my advanced task submission
=> Submission of advanced task

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Advanced Task/User Experience Research.md
This user research document details the studies and findings done to evaluate the usability and user satisfaction of the app that is to be designed.
=> User Experience Research Document

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Advanced Task/Brand Identity Design.md
To ensure a uniform and consistent design language for the app, I decided to create a small-scale brand identity for the app.
=> Brand Identity Design

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Advanced Task/User Interface Design.md
I used Figma to design a select number of screens that highlight the app's key features and functionality.
=> User Interface Design in Figma

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Advanced Task/Branding and UI design.md
This file encompasses my branding and UI submission for the advanced task. It covers the brand name, color, logo, style guide, hifi design and prototype.
=> Created a file for branding and UI design

Create a platform to link-up medical facilities globally/Tasks/Ihimbru Kanyimi Ihimbru/Advanced Task
github repo to app to link medical facilities globally, contains figma design and flutter code
=> Create Advanced Task

Create a platform to link-up medical facilities globally/Applicants/Emmanuella Abubakar/Advanced Task/Development.md
This file majorly covers the tools i used for building the project, the process i took, the link to the app codebase and the video of the app.
=> Created a file for the app development

Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Advance Task/PrototypeModel.md, Create a platform to link-up medical facilities globally/Applicants/Anisha Singh/Advance Task/ResearchTask0.md
👋 Hello, @PetraAG 
**You can find the link to my Flutter Prototype Repository here** 👇
https://github.com/AnishaSingh0118/AdvanceTask
**Attaching the video here:** 
https://user-images.githubusercontent.com/76876709/229575948-ae7f0089-6e48-413f-8319-cc7d8cf67033.mp4
=> Advance Task (Prototype Model For #Project 1)

Create a platform to link-up medical facilities globally/Applicants/Joseph Sa-Ambo/Advanced Task/Flutter App Development.md
Flutter App Development for Medical Application.
=> Flutter App Dev

Create a platform to link-up medical facilities globally/Applicants/Earl-Millen Toh Akwe/Create a platform to link medical facilities globally/Advance Task/task.md
final contributions to the link up task in the advance task , creating a web and mobile app as solution to this task
=> advance task for linkup project

Create a platform to link-up medical facilities globally/Applicants/Nuibim Lewin/Advanced Task/proposed_design.md
Hello, Here is a PR with a proposed Design for the application to link up medical facilities worldwide.
=> Advanced Task - Submitted Proposed Design for Application to Link Up Medical Facilities WorldWide

Open Pay-The Open Source Payment technology for small change scarcity Mentor actions/Applicants/RICHARD DUSHIME/Advanced Task/Brand Identity Suggestions.md
Greetings @Fadanka @ruqaiyasattar @PetraAG @jafsia 
Hope you are All doing Well 
In this PR i listed down  Names that would best fit to be Brand Names for Open pay Project including Names in African Languages Got through research  as it was suggested [Here](https://github.com/Mboalab/Outreachy_May_2023-August_2023-Internships/pull/192) by @Fadanka 
Hope you find it useful 
i would also Highly Appreciate your suggestions As i was still planning to make Poll for the suggested list  to get inputs from other people also since getting a Brand Name involves our target audiences
Thank you All for your time and Review
=> Brand Name Suggestions  
